apiVersion: v1
kind: service
metadata:
     name: nginx
	 namespace: nginx
	 labels:
	    app: nginx
spec:
   type: NodePort
   ports: 
      ports: 80
	  nodePort: 30225
   selector:
       name: nginx
